steps:
- uses: actions/checkout@v2
- uses: actions/download-artifact@master
  with: 
    name: webpack artifacts
    path: public
- name: Use Node.js ${{ matrix.node-version }}
  uses: actions/setup-node@v1
  with:
    node-version: ${{ matrix.node-version }}
- name: npm install, and test
  run: |
    npm install
    npm test
  env:
    CI: true
